/* eslint-disable unicorn/numeric-separators-style */

export const factors = ['ext', 'agr', 'csn', 'est', 'opn'] as const;
export type Factor = (typeof factors)[number];

export const factorLabels: Record<Factor, string[]> = {
	ext: ['Extraversion', 'Surgency'],
	agr: ['Agreeableness'],
	csn: ['Conscientiousness'],
	est: ['Emotional Stability'],
	opn: ['Intellect', 'Imagination', 'Openness'],
};

export const factorDescriptions: Record<Factor, string> = {
	ext: 'Individuals who score high on Extraversion tend to be sociable, talkative, assertive, and active; those who score low tend to be retiring, reserved, and cautious.',
	agr: 'Individuals who score high on Agreeableness tend to be good-natured, compliant, modest, gentle, and cooperative. Individuals who score low on this dimension tend to be irritable, ruthless, suspicious, and inflexible.',
	opn: 'Individuals who score high on this dimension tend to be intellectual, imaginative, sensitive, and open-minded. Those who score low tend to be down-to-earth, insensitive, and conventional.',
	est: 'Individuals high on Emotional Stability tend to be calm, poised, and emotionally stable. Those low on Emotional Stability tend to be anxious, depressed, angry, and insecure.',
	csn: 'Individuals high in Conscientiousness tend to be careful, thorough, responsible, organized, and scrupulous. Those low on this dimension tend to be irresponsible, disorganized, and unscrupulous.',
};

export interface Marker {
	factor: Factor;
	text: `I ${string}.`;
	negative: boolean;
}

export const markers50: Marker[] = [
	{ factor: 'ext', text: 'I am the life of the party.', negative: false },
	{ factor: 'ext', text: 'I feel comfortable around people.', negative: false },
	{ factor: 'ext', text: 'I start conversations.', negative: false },
	{ factor: 'ext', text: 'I talk to a lot of different people at parties.', negative: false },
	{ factor: 'ext', text: "I don't mind being the center of attention.", negative: false },
	{ factor: 'ext', text: "I don't talk a lot.", negative: true },
	{ factor: 'ext', text: 'I keep in the background.', negative: true },
	{ factor: 'ext', text: 'I have little to say.', negative: true },
	{ factor: 'ext', text: "I don't like to draw attention to myself.", negative: true },
	{ factor: 'ext', text: 'I am quiet around strangers.', negative: true },

	{ factor: 'agr', text: 'I am interested in people.', negative: false },
	{ factor: 'agr', text: "I sympathize with others' feelings.", negative: false },
	{ factor: 'agr', text: 'I have a soft heart.', negative: false },
	{ factor: 'agr', text: 'I take time out for others.', negative: false },
	{ factor: 'agr', text: "I feel others' emotions.", negative: false },
	{ factor: 'agr', text: 'I make people feel at ease.', negative: false },
	{ factor: 'agr', text: 'I am not really interested in others.', negative: true },
	{ factor: 'agr', text: 'I insult people.', negative: true },
	{ factor: 'agr', text: "I am not interested in other people's problems.", negative: true },
	{ factor: 'agr', text: 'I feel little concern for others.', negative: true },

	{ factor: 'csn', text: 'I am always prepared.', negative: false },
	{ factor: 'csn', text: 'I pay attention to details.', negative: false },
	{ factor: 'csn', text: 'I get chores done right away.', negative: false },
	{ factor: 'csn', text: 'I like order.', negative: false },
	{ factor: 'csn', text: 'I follow a schedule.', negative: false },
	{ factor: 'csn', text: 'I am exacting in my work.', negative: false },
	{ factor: 'csn', text: 'I leave my belongings around.', negative: true },
	{ factor: 'csn', text: 'I make a mess of things.', negative: true },
	{
		factor: 'csn',
		text: 'I often forget to put things back in their proper place.',
		negative: true,
	},
	{ factor: 'csn', text: 'I shirk my duties.', negative: true },

	{ factor: 'est', text: 'I am relaxed most of the time.', negative: false },
	{ factor: 'est', text: 'I seldom feel blue.', negative: false },
	{ factor: 'est', text: 'I get stressed out easily.', negative: true },
	{ factor: 'est', text: 'I worry about things.', negative: true },
	{ factor: 'est', text: 'I am easily disturbed.', negative: true },
	{ factor: 'est', text: 'I get upset easily.', negative: true },
	{ factor: 'est', text: 'I change my mood a lot.', negative: true },
	{ factor: 'est', text: 'I have frequent mood swings.', negative: true },
	{ factor: 'est', text: 'I get irritated easily.', negative: true },
	{ factor: 'est', text: 'I often feel blue.', negative: true },

	{ factor: 'opn', text: 'I have a rich vocabulary.', negative: false },
	{ factor: 'opn', text: 'I have a vivid imagination.', negative: false },
	{ factor: 'opn', text: 'I have excellent ideas.', negative: false },
	{ factor: 'opn', text: 'I am quick to understand things.', negative: false },
	{ factor: 'opn', text: 'I use difficult words.', negative: false },
	{ factor: 'opn', text: 'I spend time reflecting on things.', negative: false },
	{ factor: 'opn', text: 'I am full of ideas.', negative: false },
	{ factor: 'opn', text: 'I have difficulty understanding abstract ideas.', negative: true },
	{ factor: 'opn', text: 'I am not interested in abstract ideas.', negative: true },
	{ factor: 'opn', text: 'I do not have a good imagination.', negative: true },
];

export const markers100: Marker[] = [
	{ factor: 'ext', text: 'I am the life of the party.', negative: false },
	{ factor: 'ext', text: 'I feel comfortable around people.', negative: false },
	{ factor: 'ext', text: 'I start conversations.', negative: false },
	{ factor: 'ext', text: 'I talk to a lot of different people at parties.', negative: false },
	{ factor: 'ext', text: "I don't mind being the center of attention.", negative: false },
	{ factor: 'ext', text: 'I make friends easily.', negative: false },
	{ factor: 'ext', text: 'I take charge.', negative: false },
	{ factor: 'ext', text: 'I know how to captivate people.', negative: false },
	{ factor: 'ext', text: 'I feel at ease with people.', negative: false },
	{ factor: 'ext', text: 'I am skilled in handling social situations.', negative: false },
	{ factor: 'ext', text: "I don't talk a lot.", negative: true },
	{ factor: 'ext', text: 'I keep in the background.', negative: true },
	{ factor: 'ext', text: 'I have little to say.', negative: true },
	{ factor: 'ext', text: "I don't like to draw attention to myself.", negative: true },
	{ factor: 'ext', text: 'I am quiet around strangers.', negative: true },
	{ factor: 'ext', text: 'I find it difficult to approach others.', negative: true },
	{ factor: 'ext', text: 'I often feel uncomfortable around others.', negative: true },
	{ factor: 'ext', text: 'I bottle up my feelings.', negative: true },
	{ factor: 'ext', text: 'I am a very private person.', negative: true },
	{ factor: 'ext', text: 'I wait for others to lead the way.', negative: true },

	{ factor: 'agr', text: 'I am interested in people.', negative: false },
	{ factor: 'agr', text: "I sympathize with others' feelings.", negative: false },
	{ factor: 'agr', text: 'I have a soft heart.', negative: false },
	{ factor: 'agr', text: 'I take time out for others.', negative: false },
	{ factor: 'agr', text: "I feel others' emotions.", negative: false },
	{ factor: 'agr', text: 'I make people feel at ease.', negative: false },
	{ factor: 'agr', text: "I inquire about others' well-being.", negative: false },
	{ factor: 'agr', text: 'I know how to comfort others.', negative: false },
	{ factor: 'agr', text: 'I love children.', negative: false },
	{ factor: 'agr', text: 'I am on good terms with nearly everyone.', negative: false },
	{ factor: 'agr', text: 'I have a good word for everyone.', negative: false },
	{ factor: 'agr', text: 'I show my gratitude.', negative: false },
	{ factor: 'agr', text: 'I think of others first.', negative: false },
	{ factor: 'agr', text: 'I love to help others.', negative: false },
	{ factor: 'agr', text: 'I insult people.', negative: true },
	{ factor: 'agr', text: "I am not interested in other people's problems.", negative: true },
	{ factor: 'agr', text: 'I feel little concern for others.', negative: true },
	{ factor: 'agr', text: 'I am not really interested in others.', negative: true },
	{ factor: 'agr', text: 'I am hard to get to know.', negative: true },
	{ factor: 'agr', text: 'I am indifferent to the feelings of others.', negative: true },

	{ factor: 'csn', text: 'I am always prepared.', negative: false },
	{ factor: 'csn', text: 'I pay attention to details.', negative: false },
	{ factor: 'csn', text: 'I get chores done right away.', negative: false },
	{ factor: 'csn', text: 'I like order.', negative: false },
	{ factor: 'csn', text: 'I follow a schedule.', negative: false },
	{ factor: 'csn', text: 'I am exacting in my work.', negative: false },
	{ factor: 'csn', text: 'I do things according to a plan.', negative: false },
	{ factor: 'csn', text: 'I continue until everything is perfect.', negative: false },
	{ factor: 'csn', text: 'I make plans and stick to them.', negative: false },
	{ factor: 'csn', text: 'I love order and regularity.', negative: false },
	{ factor: 'csn', text: 'I like to tidy up.', negative: false },
	{ factor: 'csn', text: 'I leave my belongings around.', negative: true },
	{ factor: 'csn', text: 'I make a mess of things.', negative: true },
	{
		factor: 'csn',
		text: 'I often forget to put things back in their proper place.',
		negative: true,
	},
	{ factor: 'csn', text: 'I shirk my duties.', negative: true },
	{ factor: 'csn', text: 'I neglect my duties.', negative: true },
	{ factor: 'csn', text: 'I waste my time.', negative: true },
	{ factor: 'csn', text: 'I do things in a half-way manner.', negative: true },
	{ factor: 'csn', text: 'I find it difficult to get down to work.', negative: true },
	{ factor: 'csn', text: 'I leave a mess in my room.', negative: true },

	{ factor: 'est', text: 'I am relaxed most of the time.', negative: false },
	{ factor: 'est', text: 'I seldom feel blue.', negative: false },
	{ factor: 'est', text: 'I am not easily bothered by things.', negative: false },
	{ factor: 'est', text: 'I rarely get irritated.', negative: false },
	{ factor: 'est', text: 'I seldom get mad.', negative: false },
	{ factor: 'est', text: 'I get stressed out easily.', negative: true },
	{ factor: 'est', text: 'I worry about things.', negative: true },
	{ factor: 'est', text: 'I am easily disturbed.', negative: true },
	{ factor: 'est', text: 'I get upset easily.', negative: true },
	{ factor: 'est', text: 'I change my mood a lot.', negative: true },
	{ factor: 'est', text: 'I have frequent mood swings.', negative: true },
	{ factor: 'est', text: 'I get irritated easily.', negative: true },
	{ factor: 'est', text: 'I often feel blue.', negative: true },
	{ factor: 'est', text: 'I get angry easily.', negative: true },
	{ factor: 'est', text: 'I panic easily.', negative: true },
	{ factor: 'est', text: 'I feel threatened easily.', negative: true },
	{ factor: 'est', text: 'I get overwhelmed by emotions.', negative: true },
	{ factor: 'est', text: 'I take offense easily.', negative: true },
	{ factor: 'est', text: 'I get caught up in my problems.', negative: true },
	{ factor: 'est', text: 'I grumble about things.', negative: true },

	{ factor: 'opn', text: 'I have a rich vocabulary.', negative: false },
	{ factor: 'opn', text: 'I have a vivid imagination.', negative: false },
	{ factor: 'opn', text: 'I have excellent ideas.', negative: false },
	{ factor: 'opn', text: 'I am quick to understand things.', negative: false },
	{ factor: 'opn', text: 'I use difficult words.', negative: false },
	{ factor: 'opn', text: 'I spend time reflecting on things.', negative: false },
	{ factor: 'opn', text: 'I am full of ideas.', negative: false },
	{ factor: 'opn', text: 'I carry the conversation to a higher level.', negative: false },
	{ factor: 'opn', text: 'I catch on to things quickly.', negative: false },
	{ factor: 'opn', text: 'I can handle a lot of information.', negative: false },
	{ factor: 'opn', text: 'I love to think up new ways of doing things.', negative: false },
	{ factor: 'opn', text: 'I love to read challenging material.', negative: false },
	{ factor: 'opn', text: 'I am good at many things.', negative: false },
	{ factor: 'opn', text: 'I have difficulty understanding abstract ideas.', negative: true },
	{ factor: 'opn', text: 'I am not interested in abstract ideas.', negative: true },
	{ factor: 'opn', text: 'I do not have a good imagination.', negative: true },
	{ factor: 'opn', text: 'I try to avoid complex people.', negative: true },
	{ factor: 'opn', text: 'I have difficulty imagining things.', negative: true },
	{ factor: 'opn', text: 'I avoid difficult reading material.', negative: true },
	{ factor: 'opn', text: 'I will not probe deeply into a subject.', negative: true },
];

export const norms: Record<Factor, { mean: number; stddev: number }> = {
	ext: { mean: 30.23495547368774, stddev: 3.8609638309827847 },
	agr: { mean: 31.554468515861945, stddev: 4.022586469232606 },
	csn: { mean: 31.23387709435474, stddev: 4.284491089810227 },
	est: { mean: 30.241396150984947, stddev: 6.7333246012644565 },
	opn: { mean: 32.658302731565435, stddev: 4.296048595901091 },
};
